---
name: Docs
on:
  push:
    branches:
      - master
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Link Checker
        uses: peter-evans/link-checker@v1.2.2
        with:
          args: -v -r -d ${{ GITHUB_WORKSPACE }} -r ${{ GITHUB_WORKSPACE }}
      - name: Fail if there were link errors
        run: exit ${{ steps.lc.outputs.exit_code }}